### ISSUE TITLE
Habitability mask during Input creation

### ISSUE THREAD

**Issue by benj919** [project-gen3sis/R-package#11]
Currently the habitability mask in the input creation overrides the habitable cells in the landscape rasters. This is going to be inconsistent with NA-cells in the input rasters as these are used to determine habitable cells during the simulation run.

I think a better/more intuitive way would be to use the habitability mask in addition to the landscapes, as such that for example it allows to limit the world to a smaller extract.

**Comment by ohagen** [comment]
This would change the input_creation script and vignette. Should we do it before CRAN submission?
