### ISSUE TITLE
Missing help file 

### ISSUE THREAD

**Issue by florianhartig** [project-gen3sis/R-package#19]
`Warning: [/Users/florian/Dropbox/Home/Projekte/Papers_in_Review/19-rGAsm-package/R-package/R/observations.R:146] @example '/Users/florian/Dropbox/Home/Projekte/Papers_in_Review/19-rGAsm-package/R-package/inst/examples/observer_plot_help.R' doesn't exist`

-> should I add the file?

**Comment by florianhartig** [comment]
OK, I have created an empty file now - needs to be populated!

**Comment by ohagen** [comment]
Thanks! I will have to go though this! and will take extra care with the long running examples.
