### ISSUE TITLE
add travis win build 

### ISSUE THREAD

**Issue by ohagen** [project-gen3sis/R-package#23]
add windows and possibly mac flavours on CI travis

**Comment by florianhartig** [comment]
I think Windows doesn't work with Travis (at least didn't used to) but may be working with actions in GH, see https://github.com/TheoreticalEcology/s-jSDM/actions

**Comment by florianhartig** [comment]
Mac should be possible with travis though

**Comment by benj919** [comment]
Travis supports windows builds since somewhat recently:
https://blog.travis-ci.com/2018-10-11-windows-early-release
Though I haven't checked whether it supports R or other dependencies.

**Comment by ohagen** [comment]
Benji, can you have a look at this?

**Comment by florianhartig** [comment]
yes, it supports windows, but I think not Windows + R. But I'm not sure, check for yourself.

**Comment by florianhartig** [comment]
But as said, I think it would be possible to do windows checks with GH. That being said - I don't think it's particularly crucial to have builds for all OS, there are very few OS specific problems in a typical project, in 95% of cases you will be fine with the 3 linux builds

**Comment by benj919** [comment]
https://docs.travis-ci.com/user/languages/r#r-versions
Travis CI supports R versions 3.0.3 and above on Ubuntu Precise, Ubuntu Trusty and macOS.
