### ISSUE TITLE
Build error due to create_input.Rmd

### ISSUE THREAD

**Issue by florianhartig** [project-Gen3sis/R-package#25]
Hi Juliano, this file currently doesn't run, probably due to #24 

No problem, but now that we have the CI running, to be able to check the model, it would be better move this file into a new branch, so that we have the master branch clean / can check if everything works fine. 

I can do it for you, I just didn't want to do it in case you are currently working on it.

**Comment by julianoscabral** [comment]
ok, I created another branch to work on #24.
