### ISSUE TITLE
add to imports

### ISSUE THREAD

**Issue by ohagen** [project-gen3sis/R-package#34]
* checking R code for possible problems ... NOTE
conditional_plot : <anonymous>: no visible global function definition
  for 'is'
conditional_plot: no visible global function definition for 'png'
Undefined global functions or variables:
  is png
Consider adding
  importFrom("grDevices", "png")
  importFrom("methods", "is")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports field
contains 'methods').

**Comment by benj919** [comment]
fixed with e251d9b
