### ISSUE TITLE
vignette problems in CRAN Should be corrected by 2021-10-19 to safely retain gen3sis on CRAN.

### ISSUE THREAD

**Issue by ohagen** [project-gen3sis/R-package#54]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_gen3sis.html>.

The vignette problems are from vignettes that contain unbalanced code chunk delimiters (e.g., a chunk opened by five backticks but closed by four, or opened by three but closed by four, etc.).

See <https://github.com/yihui/knitr/issues/2057> for more information.

Please correct before 2021-10-19 to safely retain your package on CRAN.

**Comment by yihui** [comment]
The PR #54 should fix it. Thanks!
