### ISSUE TITLE
CRAN complain for non-standard things in the check directory ... NOTE

### ISSUE THREAD

**Issue by ohagen** [project-Gen3sis/R-package#6]
```
* checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  'examples_i386' 'examples_x64' 'gen3sis-Ex_i386.Rout'
  'gen3sis-Ex_x64.Rout' 'tests_i386' 'tests_x64'
```

The above happens when checking the package.

**Comment by florianhartig** [comment]
So, for me, the CRAN checks break already with the vignette, at 

```{r eval=TRUE}
# TOADD a plot of richenss over time
load(file.path(datapath, "output/config_rte/sgen3sis.RData"))
#get total richness per time interval
rt <- colSums(sgen3sis$geo_richness[,-c(1,2)], na.rm = T)
#plot
plot(rt, type='l')
```

are you sure that this is running through? Regardless, to fix this, first thing I would do is to get the CI running (see https://github.com/project-Gen3sis/R-package/issues/9), this will give you a good hint how things look on a clean system, and then we can take it from there.

**Comment by ohagen** [comment]
I will update the vignette. Never did CI, so happy to support you as you tell me.

**Comment by ohagen** [comment]
Vignette should be working now. I changed the output system but still had the old sgen3sis object on my package folder! Thanks for spotting this out. Should work now regarding the vignette. Let me know what I should do regarding the CI

**Comment by florianhartig** [comment]
So, I don't get any of these non-standard files in my tests. Are you still getting this?

**Comment by florianhartig** [comment]
I think this is something from your local computers - do you actually see these files? Have you tried just erasing them?

**Comment by benj919** [comment]
I don't get this, but I'm on Ubuntu. Initially those files only showed up when checking with R-devel iirc...

**Comment by florianhartig** [comment]
So, who exactly can reproduce this problem, and if someone can reproduce it, could you describe exactly the circumstances under which this occurs?

If no one can reproduce it, I guess we should close this!

**Comment by florianhartig** [comment]
Oskar, check again if #25 is solved, I expect that this will be gone

**Comment by ohagen** [comment]
#25 is fixed. Thanks! Can we close this? What do you get on mac when checking on -as --CRAN?

**Comment by florianhartig** [comment]
In never got a problem. Will close, you can re-open if this is showing up in any of the tests
