### ISSUE TITLE
accounting problem for speciation followed by extinction

### ISSUE THREAD

**Issue by wibach** [project-gen3sis/R-package#63]
I found an issue where a species dies at timestep t, and speciates at t+1 (t-1 in backwards counting steps).

**Comment by ohagen** [comment]
Hi Mine,
Can you specify? I guess you already talked with Benjamin and Alex about this? 
Feel free to e-mail or zoom me anytime...
Cheers

**Comment by ohagen** [comment]
Closing for the moment as we still lack an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) and/or further information is necessary.

**Comment by benj919** [comment]
Species 1 dies at 638, speciates 4 in 637
Species 6 dies at 588, speciates  23 in 587

[phy.nex.txt](https://github.com/project-gen3sis/R-package/files/10169007/phy.nex.txt)
[phy.txt](https://github.com/project-gen3sis/R-package/files/10169008/phy.txt)

**Comment by ohagen** [comment]
Thanks Benji!
Let me know if you need a hand looking into it. Curious to hear more.

**Comment by ohagen** [comment]
short re-opening referent to the possible unnecessary files.
