### ISSUE TITLE
Automatic tests / continuous integration

### ISSUE THREAD

**Issue by florianhartig** [project-Gen3sis/R-package#9]
Hi guys,

just as we talked about the tests -  you haven't set up CI tests yet, right? There are at least two options, Travis CI, which I do for DHARMa, and there is a new option directly via GitHub workflows, see an example here https://github.com/TheoreticalEcology/s-jSDM/actions

The advantage of using the workflows is that a) I think it can also be done on a private repo b) it also tests Windows and MacOS. Advantage of TravisCI is that it looks nicer (in my opinion), especially when you work a lot with branches. 

Anyway, we should decide for one or the other, this will help a lot with the tests and questions such as #6

**Comment by florianhartig** [comment]
Both are free for open source projects ... because it's faster, I will now add a Travis file, and you can add the workflow if you find the time, we can then see what works better.

**Comment by florianhartig** [comment]
I have pushed a Travis file, but I think the owner of the repo has to activate this, at least I can't see the results. I requested the rights from you too.

**Comment by ohagen** [comment]
access granted

**Comment by florianhartig** [comment]
no, that didn't work, I don't have the rights. Do you see something at https://travis-ci.com/github/project-Gen3sis/R-package ?

**Comment by florianhartig** [comment]
I still can't do it - I think you have to activate it Oskar - I can know see now 

https://travis-ci.org/github/project-Gen3sis/R-package

but I'm getting 

```
This is not an active repository
You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself.
```

**Comment by florianhartig** [comment]
Hi all, continous integration is working now, ideally sign up to Travis so that you get emails when a build fails, or else check whenever you commit something https://travis-ci.com/github/project-Gen3sis/R-package/branches 

The link is also on the main page.

I have mentioned this before, in order to make this work properly, any time you implement a new feauture

* create a branch
* do your changes in the branch
* publish the branch, or better: create a pull request, which will trigger the CI tests to run
* if it works, merge back into the master branch

If you do this systematically, the master branch should always be clean / working!
